# Generated by Django 6.0.3 on 2026-03-22 10:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('proof_description', models.TextField(help_text="Claimant's detailed description of the item (color, brand, marks, contents).")),
                ('proof_identifiers', models.TextField(help_text='Unique identifiers provided by claimant: serial number, name tag, contents of wallet, etc.')),
                ('additional_notes', models.TextField(blank=True, help_text='Any extra context from the claimant.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('security_notes', models.TextField(blank=True, help_text='Internal security notes — not shown to claimant.')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='items.item')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('item', 'claimant')},
            },
        ),
        migrations.CreateModel(
            name='CustodyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('storage_location', models.CharField(default='Security Office — Main Cabinet', max_length=200)),
                ('custody_status', models.CharField(choices=[('in_custody', 'In Custody'), ('claimed', 'Claimed — Pending Handover'), ('returned', 'Returned to Owner'), ('disposed', 'Disposed / Donated')], db_index=True, default='in_custody', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('secret_identifiers', models.TextField(blank=True, help_text='Hidden details: serial numbers, contents, personal marks. NOT shown publicly. Used to verify claimants.')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custody', to='items.item')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='HandoverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_name', models.CharField(max_length=200)),
                ('collector_id_number', models.CharField(help_text='Student ID / Staff ID / National ID', max_length=100)),
                ('collector_id_type', models.CharField(choices=[('student_id', 'Student ID'), ('staff_id', 'Staff ID'), ('national_id', 'National ID'), ('other', 'Other')], default='student_id', max_length=50)),
                ('handed_over_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='security.claimrequest')),
                ('handed_over_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_given', to=settings.AUTH_USER_MODEL)),
                ('handed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='items.item')),
            ],
            options={
                'ordering': ['-handed_over_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('false_claim', 'False Claim'), ('spam', 'Spam / Fake Post'), ('suspicious', 'Suspicious Activity'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='security.claimrequest')),
                ('related_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='items.item')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=50, unique=True)),
                ('office_location', models.CharField(default='Main Security Office', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
